version: "3"

services:
  visualizer:
    image: dockersamples/visualizer:stable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    networks:
      - my-network
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1

  customer-api:
    image: olgac/customer-api:1.0 
    ports:
      - 5001:8080
    networks:
      - my-network
    deploy:
      replicas: 4

  merchant-api:
    image: olgac/merchant-api:1.0
    ports:
      - 5002:8080
    networks:
      - my-network
    depends_on:
      - redis
    deploy:
      replicas: 3

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - my-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  my-network: