version: "3"

services:
  l5d:
    image: buoyantio/linkerd:1.3.5
    ports:
      - "4140:4140"
      - "9990:9990"
    networks:
      - my-network
    volumes:
      - /var/git/linkerd.yaml:/io.buoyant/linkerd.yaml
    deploy:
      mode: global
    command: >
      /io.buoyant/linkerd.yaml

  visualizer:
    image: dockersamples/visualizer:stable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    networks:
      - my-network
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure

  customer-api:
    image: olgac/customer-api:1.0
    volumes:
     - /var/log/:/var/log/
     - /var/empty/:/var/empty/
    ports:
      - 5001:8080
    networks:
      - my-network
    depends_on:
      - redis
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  merchant-api:
    image: olgac/merchant-api:1.0
    volumes:
     - /var/log/:/var/log/
     - /var/empty/:/var/empty/
    ports:
      - 5002:8080
    networks:
      - my-network
    depends_on:
      - redis
    deploy:
      placement:
        constraints: [node.role == manager]
      replicas: 3
      update_config:
        parallelism: 3
      restart_policy:
        condition: on-failure

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - my-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  my-network: