apiVersion: v1
kind: Service
metadata:
  name: merchant-api-service
  namespace: default
spec:
  selector:
    app: merchant-api
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080