apiVersion: v1
kind: Service
metadata:
  name: merchant-api-service
  namespace: default
spec:
  selector:
    app: merchant-api
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30000
